### ISSUE TITLE
Add Copy to Clipboard

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion#14]
Add a copy-to-clipboard button for code blocks

https://codinasion.org/program/add-two-matrices

![Screenshot from 2023-02-20 10-09-26](https://user-images.githubusercontent.com/54644599/220010961-83f9acca-5e92-47bb-912d-e09858dacba7.png)

**Comment by Kise07** [comment]
I want to work on this issue as my first contribution. Please! Could you tell me more about what process I need to complete? Step-wise.

**Comment by Yarnacle** [comment]
could I be assigned?

**Comment by Yarnacle** [comment]
I originally thought this would be a simple React operation but it involves remarkjs, so it seems a seemingly simple task of adding a copy button is actually a little complex.

Possible solutions:

1. Use a plugin
2. Make a plugin
3. Override a Pre component(?)
4. Script that iteratively changes code blocks to include copy button - I belive this should be seen as a last resort as it is very lazy and hard to maintain

After having spent considerable time reading through the code, I have failed to gain a fairly complete understanding of how exactly the code blocks are rendered

**Comment by harshraj8843** [comment]
The `CodeBlock` component is basically a collection of the `Code` components.

I have not added a `CopyToClipboard` button before, but I think, we have to add a button in the `Code` component and align it using `Tailwind CSS`

https://github.com/codinasion/codinasion/blob/9437ee5d84d2cd1bedfd0200f2aaf2456893bf4c/src/components/MarkdownPreview/Code.tsx#L17-L32

**Comment by harshraj8843** [comment]
@0ME9A Could you help 🙏🏻

**Comment by harshraj8843** [comment]
Maybe, @0ME9A's approach will help

https://github.com/codinasion/codinasion-tools/blob/86401f8768c957e034d9d10116f9d1aa3b7633d8/website/src/components/ToolsComps/ToolsDocs.tsx#L15-L25
