### ISSUE TITLE
Codinasion Website Working Model

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion#214]
### Title of article

Should we show solution in multiple language in same page for a specific question ?

### Model we are using now : 

Let's see for a `Hello World` programme. Solutions are available at

- `c/programme/hello-world`
- `python/programme/hello-world`
- `c++/programme/hello-world`
- `c#/programme/hello-world`
- `java/programme/hello-world`

### Suggestion

We can create a dedicated folder for specific problem (`programme/hello-world`) and all solution can be available in a single folder like : 

- `programme/hello-world/solution.c`
- `programme/hello-world/solution.py`
- `programme/hello-world/solution.cpp`
- `programme/hello-world/solution.cs`
- `programme/hello-world/solution.java`

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Please suggest @harshi1122 @aryangupta701 @debaghosh @PA11TEDDU @iUttamRao and all

**Comment by debaghosh** [comment]
Yeah, putting all the codes in one folder will probably be more efficient 🙌

**Comment by Satyapriyo** [comment]
Yes you are right @harshraj8843 this suggestion can improve user experience  also will be helpful for beginners. 👍👍

**Comment by Satyapriyo** [comment]
If you want i can merge a request after making this changes

**Comment by harshi1122** [comment]
> ### Title of article
> Should we show solution in multiple language in same page for a specific question ?
> 
> ### Additional information
> ### Model we are using now :
> Let's see for a `Hello World` programme. Solutions are available at
> 
> * `c/programme/hello-world`
> * `python/programme/hello-world`
> * `c++/programme/hello-world`
> * `c#/programme/hello-world`
> * `java/programme/hello-world`
> 
> ### Suggestion
> We can create a dedicated folder for specific problem (`programme/hello-world`) and all solution can be available in a single folder like :
> 
> * `programme/hello-world/solution.c`
> * `programme/hello-world/solution.py`
> * `programme/hello-world/solution.cpp`
> * `programme/hello-world/solution.cs`
> * `programme/hello-world/solution.java`
> 
> ### Code of Conduct
> * [x]  I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

I agree with the single folder suggestion 
Will help users find everything in one place rather than having to switch back and forth to find the same program in another language.

**Comment by harshi1122** [comment]
> Please suggest @harshi1122 @aryangupta701 @debaghosh @PA11TEDDU @iUttamRao @Satyapriyo and all

I agree with the single folder suggestion
Will help users find everything in one place rather than having to switch back and forth to find the same program in another language.

**Comment by harshraj8843** [comment]
Please check this sample page.

` Preview ` : https://codinasion--pr15-dev-2xs9bp16.web.app/programme/

**Comment by harshi1122** [comment]
> Please check this sample page.
> 
> `Preview` : https://codinasion--pr15-dev-2xs9bp16.web.app/programme/

Great! 💯

**Comment by Satyapriyo** [comment]
It's great man

**Comment by harshraj8843** [comment]
So, i am gonna work on it.

Till then all PR will be in queue 😃

**Comment by iUttamRao** [comment]
Yeah It's good
