### ISSUE TITLE
Add hover animations to Project components

### ISSUE THREAD

**Issue by Petrosdevri** [codinasion/codinasion#22]
I would like to add some hover animations to Project components (probably scale them with the transform property). It's a well-known and commonly used pattern to improve user experience.

**Comment by harshraj8843** [comment]
Sure @Petrosdevri

**Comment by Petrosdevri** [comment]
I am working on the hover animations and have developed most of them, however they don't appear for some errors I don't understand. One of the main explanations is that there hasn't been a <code>styles.css</code> file generated in the <code>public</code> folder. I would like to ask how do you update these changes in Tailwind as rest of the code seems to work fine.

**Comment by harshraj8843** [comment]
Hey @Petrosdevri 

I am unable to understand the error

Could you raise a PR for the changes you have made? It would be much easier to understand the error with the code
