### ISSUE TITLE
Python info not showing under Python tab

### ISSUE THREAD

**Issue by debaghosh** [codinasion/codinasion#222]
### Description

Python info is not being shown when we select the Python tab.

### Screenshots

![Screenshot_20220223_163147](https://user-images.githubusercontent.com/42775082/155307565-a80625dc-738d-41c8-83a1-f082a925dc6a.jpg)

**Comment by harshraj8843** [comment]
Thanks for your feedback.

This issue has been `fixed`.

Feel free to let us know about any other issue.
