### ISSUE TITLE
Improve Footer

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion#3]
Improve `Footer` component of [`https://codinasion.org`](https://codinasion.org/)

**Comment by Veronica0014** [comment]
Hi, May I try?

**Comment by harshraj8843** [comment]
Sure @Veronica0014 🤗

**Comment by Veronica0014** [comment]
Do you have any requirements how you'd like your footer to look like, or it's up to me?

**Comment by harshraj8843** [comment]
Mostly up to you. But, it should also show the links section as currently available (position and other properties can be modified)
