### ISSUE TITLE
Project Card hover effect does not work correctly

### ISSUE THREAD

**Issue by Yarnacle** [codinasion/codinasion#34]
### Description

On the website's main page (https://codinasion.org), the project cards under the "Explore our open source projects" header have a hover effect that looks pretty weird:
> ![output](https://user-images.githubusercontent.com/109094587/221394900-1dd8cf5b-3913-48fc-8178-fe3b3a7895ab.gif)

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](CODE_OF_CONDUCT.md)

**Comment by Yarnacle** [comment]
Could I be assigned to this issue?

**Comment by harshraj8843** [comment]
Sure @Yarnacle

**Comment by Yarnacle** [comment]
The problem occurs for all project cards, so on the projects page ([https://codihttps://codinasion.org/projects](https://codinasion.org/projects)) as well

**Comment by harshraj8843** [comment]
@Yarnacle 

All pages use the same Project Card component 👉🏻 https://github.com/codinasion/codinasion/blob/master/src/components/Projects/ProjectCard.tsx

Maybe the issue is with #25

**Comment by Yarnacle** [comment]
yeah it seems the bug was introduced in #25
