### ISSUE TITLE
Add Good 1st Issue Filter

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion#37]
- Update list of `Good 1st Issue` on click of a particular tag

[`codinasion.org/good1stissue`](https://codinasion.org/good1stissue)

![Screenshot from 2023-02-26 12-57-45](https://user-images.githubusercontent.com/54644599/221397928-a3d863bd-bd47-4272-b840-0078ac413399.png)

**Comment by Yarnacle** [comment]
Could I be assigned?

**Comment by Yarnacle** [comment]
We should probably start by implementing a filter on the backend side (so in the api repo instead of this one)

**Comment by harshraj8843** [comment]
I don't think so 🤔 

- It will increase the `API` response time.
- Vercel only allows execution of functions for `3 Seconds` only, after than function will fail

---

***A better approach would be, to filter issues in frontend***

Reference 👉🏻 https://github.com/codinasion/good-1st-issue/blob/78fdb9dd9d640530eff900fcfcd0a01931298aad/pages/index.js

**Comment by Yarnacle** [comment]
Since there isn't a massive amount of data, client side filtering may be better, actually.

I'm a little confused as to what the good1stissue part of the repo is for if it has its own repo?
And shouldn't this issue be in the other repo?

**Comment by Yarnacle** [comment]
It seems like the backend of good-1st-issue is in its own repo but why is there an index.js in that repo with a react frontend and then a bunch of frontend components for good-first-issue on this repo?

**Comment by harshraj8843** [comment]
Actually, till now all projects were deployed on separate subdomains of [`codinasion.org`](http://codinasion.org/)

But it wasn't easy to maintain all project's websites separately

So, it is decided that all (most) of our projects will be hosted on [`codinasion.org`](http://codinasion.org/) (this repo)

---

> **Note** [`Good 1st Issue`](https://good1stissue.codinasion.org/) Repo contains `Website` + `Backend` + `Github App` Code

Previously, `Good 1st Issue` was deployed on [`good1stissue.codinasion.org`](https://good1stissue.codinasion.org/)

Now, we are migrating frontend to [`codinasion.org/good1stissue`](http://codinasion.org/good1stissue)

--- 

The backend of `Good 1st Issue` will also be migrated to Codinaion's centralized backend (later)

**Comment by harshraj8843** [comment]
https://good1stissue.codinasion.org/
