### ISSUE TITLE
Fibonacci series

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion#73]
### Title of article

Write a Python program to print Fibonacci series.

### Additional information

```
Input  : 10
Output : 0 1 1 2 3 5 8 13 21 34
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

**Comment by PA11TEDDU** [comment]
### Fibonacci Series
> Takes the user input
> Initial Values for Fibonacci Series are 0 and 1
> Use for loop till n-2 
> Add the n1 and n2
> Swap the values
> Print sum

```py
n = int(input())
n1 = 0
n2 = 1
print(n1,n2,end=" ")
for i in range(0,n-2):
    sum = n1+n2
    n1 = n2
    n2 = sum
    print(sum, end=" ")
    
```

**Comment by PA11TEDDU** [comment]
> This is the more optimized one
```py
n = int(input())
n1, n2 = 0, 1
for i in range(0,n):
    print(n1, end=" ")
    n1, n2  = n2, n1+n2
```

**Comment by harshraj8843** [comment]
Hii @PA11TEDDU 

Thanks for contributing to this open source project 😃 

Could you open a pull request for this
