### ISSUE TITLE
Multiply Two Numbers

### ISSUE THREAD

**Issue by harshraj8843** [codinasion/codinasion#88]
### Title of article

Write a Python programme to multiply two numbers.

### Additional information

```
Input:  5 4
Output: 20
```

### Code of Conduct

- [X] I have read and agree to the Codinasion project's [Code of Conduct](https://github.com/codinasion/codinasion/blob/master/CODE_OF_CONDUCT.md)

**Comment by harshraj8843** [comment]
Hey @Shahzeb-A 

Thanks for showing your interest in this open source project 😃 

Please follow this :- 
- fork this repo
- create a new branch
- create a `multiply-two-numbers` folder inside `programme` folder
- add the `solution.py`
- open a pull request

Done !!! 👍🏻

**Comment by Shahzeb-A** [comment]
Check please.
